# This workflow will install Python dependencies, build documentation, lint, and
# run tests and with multiple versions of Python. For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: benchmarkocp

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .
          pip install flake8 pdoc

      # Check for python syntax errors or undefined names
      - name: Check syntax
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: true

      # For now, just verify that the documentation successfully compiles
      - name: Document
        run: pdoc ./optimalcontrol --d numpy --math -t documentation/.template/ -o documentation/

      - uses: actions/upload-pages-artifact@v1
        with:
          path: documentation/

  test:

    needs: build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .

      - name: Test
        run: pytest tests/
